### ISSUE TITLE
ST3 organize imports (and add imports) raise IndexError()

### ISSUE THREAD

**Issue by ayoub-benali** [ensime/ensime-sublime#122]
## problem

calling **_organize imports_** command it doesn't work and logs the following message in the console. The same problem happens when **_add imports_** is called, because it call directly  **_organize imports_**

```
[Ensime] 2016-11-18 14:44:34,894 [INFO ]  Refactoring succeeded, patch file: /tmp/ensime-diff-6309307069321330725.tmp
[Ensime] 2016-11-18 14:44:34,895 [INFO ]  Refactoring succeeded, patch file: /tmp/ensime-diff-6309307069321330725.tmp
Traceback (most recent call last):
  File "ensime in MY_PATH/.config/sublime-text-3/Installed Packages/Ensime.sublime-package", line 666, in message_clear_all_scala_notes
  File "ensime in MY_PATH/.config/sublime-text-3/Installed Packages/Ensime.sublime-package", line 642, in _update_note_ui
  File "ensime in MY_PATH/.config/sublime-text-3/Installed Packages/Ensime.sublime-package", line 135, in redraw_all_highlights
  File "ensime in MY_PATH/.config/sublime-text-3/Installed Packages/Ensime.sublime-package", line 117, in _invoke_all_colorers
  File "ensime in MY_PATH/.config/sublime-text-3/Installed Packages/Ensime.sublime-package", line 1071, in redraw_highlights
  File "ensime in MY_PATH/.config/sublime-text-3/Installed Packages/Ensime.sublime-package", line 1084, in redraw_status
  File "/opt/sublime_text/sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
```

## steps
1. Run sbt 
2. ensime startup in sublime text
3. Everything is good.

use the commands palette to call "ensime organize imports", nothing happens on the file and check the sublime text console

## versions
sublime text 3: build 3125
ensime-sublime: when listed from the package control it has v0.11.0 version.
ensime: in sbt's plugins added as addSbtPlugin("org.ensime"           % "sbt-ensime"      % "1.11.3")
sbt version: 0.13.13
OS: Ubuntu 16.04

**Comment by VC1995** [comment]
#130. Add Import and Organize imports work now.
