### ISSUE TITLE
code completion failing (KeyError ':type-sig')

### ISSUE THREAD

**Issue by antoine-sachet** [ensime/ensime-sublime#128]
I am running sbt 0.13 with scala 2.11.1 and ensime server 2.11 (2.0.0-SNAPSHOT).

I cannot get the code completion to work with sublime text 3 on windows 7.

Here is what I did:
* Create new folder with `src/main/scala/main.scala` (code below)
* Create `build.sbt` with `scalaVersion := "2.11.11"`
* Run `sbt ensimeConfig`
* Open folder in sublime text 3
* Start ensime server
* (Wait until indexing is over)
* Try to autocomplete in main.scala (with ctrl+space):

 ```
class cl {  
    val v = List(1,2,3)
    v.<ctrl+space here>
 }
```

I get: 

```
[Ensime] 2017-05-30 15:50:30,920 [INFO ]  request #8(sync) send - b'(:swank-rpc (swank:completions (:file "C:\\\\Users\\\\sacheta\\\\Documents\\\\Projects\\\\DI_DovetailFusion\\\\A'...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\ensime.py", line 226, in on_query_completions
    return self._invoke(view, "on_query_completions", prefix, locations)
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\ensime.py", line 190, in _invoke
    return handler(*args)
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\ensime.py", line 1263, in on_query_completions
    return self._query_completions(prefix, locations)
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\ensime.py", line 1254, in _query_completions
    completions = self.rpc.completions(source_file_info, locations[0], 100, False, False)
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\rpc.py", line 465, in wrapped
    return parser(raw)
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\rpc.py", line 32, in parse
    populate(value_map)
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\rpc.py", line 63, in populate
    self.completions = CompletionInfo.parse_list(m[":completions"])
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\rpc.py", line 22, in parse_list
    return [cls.parse(raw) for raw in raw]
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\rpc.py", line 22, in <listcomp>
    return [cls.parse(raw) for raw in raw]
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\rpc.py", line 32, in parse
    populate(value_map)
  File "C:\Users\sacheta\AppData\Roaming\Sublime Text 3\Packages\Ensime\rpc.py", line 98, in populate
    self.signature = CompletionSignature.from_raw(m[":type-sig"])
KeyError: ':type-sig'
[Ensime] 2017-05-30 15:50:30,967 [INFO ]  Server: OUT: b'15:50:30.920 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/8 o.e.s.RequestHandler - CompletionsReq(SourceFileInfo(RawFile(C:\\Users\\sacheta\\Documents\\Projects\\DI_DovetailFusion\\AutoCompleteTest\\src\\main\\scala\\main.scala),Some(...),None),48,100,false,false)\r\n'
[Ensime] 2017-05-30 15:50:30,967 [INFO ]  Server: OUT: b'15:50:30.920 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message CompletionsReq(SourceFileInfo(RawFile(C:\\Users\\sacheta\\Documents\\Projects\\DI_DovetailFusion\\AutoCompleteTest\\src\\main\\scala\\main.scala),Some(...),None),48,100,false,false) from Actor[akka://ENSIME/user/ensime-main/tcp-server/\r\n15:50:30.920 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message CompletionsReq(SourceFileInfo(RawFile(C:\\Users\\sacheta\\Documents\\Projects\\DI_DovetailFusion\\AutoCompleteTest\\src\\main\\scala\\main.scala),Some(...),None),48,100,false,false) from Actor[akka://ENSIME/user/ensime-main/tcp-server/\r\n'
[Ensime] 2017-05-30 15:50:31,226 [INFO ]  Server: OUT: b'15:50:31.226 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/8 o.e.s.RequestHandler - received handled message CompletionInfoList(,List(CompletionInfo(Some(ArrowTypeInfo((B) => (CanBuildFrom[List[Int], B, That]) => That,(scala.collection.immutable.List.B) => (scala.collection.generic.CanBuildFrom[scala.collection.immutable.List[scala.\r\n'
[Ensime] 2017-05-30 15:50:33,143 [INFO ]  request #8 took 2.222853899002075 seconds
```

Please note that my autocomplete threshold is 3.0 seconds (not the default 1.0 second).

The default autocomplete (based on other words in the file) still pops (sometimes).

Happy to share more info / do more tests if requested.

**Comment by VC1995** [comment]
This works now. Ensime-sublime has been rewritten. #130
