### ISSUE TITLE
Ensime Indexing fails

### ISSUE THREAD

**Issue by lmenezes** [ensime/ensime-sublime#142]
Hey there,

I'm running OSX 10.13.3 with Sublime 3 build 3143 and the Ensime plugin(v1.0.0) installed from Package Control, but I can't really get this to work correctly. Looking at the sever.log, I get this trace, which doesn't really gives me much to look into:
```
10:17:19.001 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
10:17:19.010 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
10:17:19.013 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
10:17:19.048 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/98/v330bz4j4bd4wyy351bl0wwr0000gp/T/vfs_cache" as temporary files store.
10:17:19.085 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:56264
10:17:19.088 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 56264
10:17:19.089 INFO  None o.e.s.PortUtil$ - creating port file: /Users/leo/dev/search-proxy/.ensime_cache/port
10:17:19.188 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
10:17:19.189 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   OS : Mac OS X
10:17:19.189 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Java : Java HotSpot(TM) 64-Bit Server VM 25.92-b14, Java(TM) SE Runtime Environment 1.8.0_92-b14
10:17:19.189 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Scala version: version 2.12.4
10:17:19.190 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Ensime : 2.0.0
10:17:19.190 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Heap Size : 3817865216
10:17:19.190 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with Scala version: 2.12.3
10:17:19.190 INFO  None o.e.s.PortUtil$ - creating port file: /Users/leo/dev/search-proxy/.ensime_cache/http
10:17:19.191 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with sbt version: 0.13.16
10:17:19.191 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built from git sha: cde49d6b8d63dc6c979a9eea3137493281a0c52c
10:17:19.191 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built on: 2017-09-24
10:17:19.192 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1:56265
10:17:20.259 INFO  None o.e.s.WebSocketFrameHandler - Handlers ready
10:17:20.575 DEBUG akka://ENSIME/user/ensime-main/$b/1 o.e.s.RequestHandler - ConnectionInfoReq
10:17:22.261 DEBUG None o.e.f.FileWatchService - init watcher
10:17:22.262 DEBUG None o.e.f.FileWatchService - start a background monitoring thread
10:17:22.263 DEBUG None o.e.f.FileWatchService - start monitoring WatchService events
10:17:22.263 DEBUG None o.e.f.FileWatchService - init watcher
10:17:22.263 DEBUG None o.e.f.FileWatchService - start a background monitoring thread
10:17:22.263 DEBUG None o.e.f.FileWatchService - start monitoring WatchService events
10:17:22.621 INFO  None c.o.o.c.e.OMemoryAndLocalPaginatedEnginesInitializer - OrientDB auto-config DISKCACHE=3,641MB (heap=3,641MB direct=3,641MB os=16,384MB), assuming maximum direct memory size equals to maximum JVM heap size
10:17:22.622 WARN  None c.o.c.u.OMemory - MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=16384m option when you start the JVM.
10:17:22.735 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq from Actor[akka://ENSIME/user/ensime-main/$b/1#335413030] in state awaitingConnectionInfoReq
10:17:22.738 DEBUG akka://ENSIME/user/ensime-main/$b/1 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),1.9.6) from Actor[akka://ENSIME/user/ensime-main/project#1413741383] in state receive
10:17:22.844 DEBUG akka://ENSIME/user/ensime-main/$b o.e.s.ConnectionHandler - received handled message FullTypeCheckCompleteEvent from Actor[akka://ENSIME/user/ensime-main/project/scalac#-913135145]
10:17:22.886 DEBUG akka://ENSIME/user/ensime-main/$b o.e.s.ConnectionHandler - received handled message AnalyzerReadyEvent from Actor[akka://ENSIME/user/ensime-main/project/$a#-630087477]
10:17:22.991 DEBUG akka://ENSIME/user/ensime-main/$b/2 o.e.s.RequestHandler - TypecheckFilesReq(List())
10:17:22.991 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message TypecheckFilesReq(List()) from Actor[akka://ENSIME/user/ensime-main/$b/2#634635646] in state handleRequests
10:17:25.941 DEBUG None o.e.i.SearchService - findStaleFileChecks
10:17:26.016 DEBUG None o.e.i.SearchService - removing 0 stale files from the index
10:17:26.368 DEBUG None o.e.i.SearchService - Indexing bases...
10:17:26.480 DEBUG None o.e.i.SearchService - indexing file:///Users/leo/.ivy2/cache/org.apache.logging.log4j/log4j-api/jars/log4j-api-2.9.1.jar
10:17:26.691 DEBUG akka://ENSIME/user/ensime-main/$b o.e.s.ConnectionHandler - received handled message SendBackgroundMessageEvent(Initializing Analyzer. Please wait...,105) from Actor[akka://ENSIME/user/ensime-main/project/scalac/$a#688978428]
10:17:26.716 DEBUG akka://ENSIME/user/ensime-main/project/scalac/$a o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent from Actor[akka://ENSIME/deadLetters] in state startup
10:17:27.034 DEBUG None o.e.i.SearchService - finished indexing file:///Users/leo/.ivy2/cache/org.apache.logging.log4j/log4j-api/jars/log4j-api-2.9.1.jar
10:17:27.037 WARN  akka://ENSIME/user/ensime-main/project o.e.c.Project - Refresh failed: java.lang.IllegalArgumentException
10:17:27.039 ERROR akka.dispatch.Dispatcher a.d.Dispatcher - 
java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.ensime.indexer.ClassfileIndexer.indexClassfile(ClassfileIndexer.scala:25)
	at org.ensime.indexer.SearchService.$anonfun$extractSymbols$1(SearchService.scala:272)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.ensime.indexer.SearchService.extractSymbols(SearchService.scala:318)
	at org.ensime.indexer.SearchService.$anonfun$extractSymbolsFromClassOrJar$4(SearchService.scala:242)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.ensime.indexer.SearchService.$anonfun$extractSymbolsFromClassOrJar$2(SearchService.scala:242)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)
	at scala.concurrent.package$.blocking(package.scala:142)
	at org.ensime.indexer.SearchService.$anonfun$extractSymbolsFromClassOrJar$1(SearchService.scala:233)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
10:22:26.714 DEBUG akka://ENSIME/user/ensime-main/project/scalac/$a o.e.c.Analyzer - received handled message SuspendAnalyzer from Actor[akka://ENSIME/user/ensime-main/project/scalac/$a#688978428] in state ready
```

Is there anything I might be doing wrong? Thanks :)

**Comment by rorygraves** [comment]
Hi,

Yes that is an awful message. It looks like the indexer cannot understand one of your jars. 

Cheers

Rory
