### ISSUE TITLE
Startup failed

### ISSUE THREAD

**Issue by schmitch** [ensime/ensime-sublime#29]
Currently I can't start ensime-sublime (client) It fails with:

```
Ensime server has encountered a fatal error: Invalid rpc request (swank:init-project).

Check the server log at /Users/schmitch/Library/Application Support/Sublime Text 2/Packages/Ensime/logs/server.log.
```
server.log is empty, however I got my server console open so there si the error:
```
11:19:27.799 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/dh/nydh9zd96d19pshvm1rvvtvh0000gn/T/vfs_cache" as temporary files store.
11:19:27.954 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.i.TcpListener - Successfully bound to /127.0.0.1:63319
11:19:27.954 INFO  akka://ENSIME/user/IO-HTTP/listener-2 s.c.s.HttpListener - Bound to localhost/127.0.0.1:0
11:19:27.955 DEBUG akka://ENSIME/user/$c/docs o.e.s.DocServer - received handled message Bound(/127.0.0.1:63319)
11:19:29.658 ERROR akka://ENSIME/user/$c/project a.a.OneForOneStrategy - exception during creation
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:596) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
	at akka.util.Reflect$.instantiate(Reflect.scala:66) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.Props.newActor(Props.scala:252) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.11-2.3.11.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.11-2.3.11.jar:na]
	... 9 common frames omitted
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/Users/schmitch/projects/envisia/envisia-erp-loki/.ensime_cache/index-1.0/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:89) ~[lucene-core-4.7.2.jar:4.7.2 1586229 - rmuir - 2014-04-10 09:00:35]
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:707) ~[lucene-core-4.7.2.jar:4.7.2 1586229 - rmuir - 2014-04-10 09:00:35]
	at org.ensime.indexer.lucene.SimpleLucene.<init>(SimpleLucene.scala:63) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.IndexService.<init>(IndexService.scala:82) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.indexer.SearchService.<init>(SearchService.scala:37) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Project.<init>(Project.scala:51) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	... 18 common frames omitted

```

Also my client.log:
```
[2015-06-24 11:18:37.818944]: Starting Ensime client (plugin version is 0.6.0)
[2015-06-24 11:18:37.819600]: Launching Ensime client socket at port 63072
[2015-06-24 11:18:39.879801]: 000023(:swank-rpc (swank:init-project) 1)
[2015-06-24 11:18:39.879945]: async_req: 1  000023(:swank-rpc (swank:init-project) 1)
[2015-06-24 11:18:39.881671]: RECV: (:return (:abort 666 "Invalid rpc request (swank:init-project)") 1)
[2015-06-24 11:18:39.881997]: on_client_async_data: [:return, [:abort, 666, u'Invalid rpc request (swank:init-project)'], 1]
[2015-06-24 11:18:39.882412]: [:return, [:abort, 666, u'Invalid rpc request (swank:init-project)'], 1]
[2015-06-24 11:18:39.882831]: handleMessage: got handler(<bound method Client.message_return of <ensime.Client object at 0x10e3aa490>>, None, None)
[2015-06-24 11:18:39.883127]: handleMessage: got handler2
[2015-06-24 11:18:39.883316]: XXX Got msg_id 1  payload [:abort, 666, u'Invalid rpc request (swank:init-project)']
[2015-06-24 11:18:39.883583]: request #1 took 0.00183415412903 seconds
[2015-06-24 11:18:39.901410]: Error shutting down ensime client:
[2015-06-24 11:19:27.800682]: reflectively found 10 message handlers: [('message_background_message', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>), ('message_clear_all_java_notes', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>), ('message_clear_all_scala_notes', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>), ('message_compiler_ready', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>), ('message_debug_event', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>), ('message_full_typecheck_finished', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>), ('message_indexer_ready', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>), ('message_java_notes', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>), ('message_return', <bound method Client.message_return of <ensime.Client object at 0x10e3a1910>>), ('message_scala_notes', <bound method Client.wrapped of <ensime.Client object at 0x10e3a1910>>)]
[2015-06-24 11:19:27.801060]: Starting Ensime client (plugin version is 0.6.0)
[2015-06-24 11:19:27.801179]: Launching Ensime client socket at port 63072
[2015-06-24 11:19:29.066347]: 000023(:swank-rpc (swank:init-project) 1)
[2015-06-24 11:19:29.066516]: async_req: 1  000023(:swank-rpc (swank:init-project) 1)
[2015-06-24 11:19:29.068165]: RECV: (:return (:abort 666 "Invalid rpc request (swank:init-project)") 1)
[2015-06-24 11:19:29.068522]: on_client_async_data: [:return, [:abort, 666, u'Invalid rpc request (swank:init-project)'], 1]
[2015-06-24 11:19:29.068687]: [:return, [:abort, 666, u'Invalid rpc request (swank:init-project)'], 1]
[2015-06-24 11:19:29.068964]: handleMessage: got handler(<bound method Client.message_return of <ensime.Client object at 0x10e3a1910>>, None, None)
[2015-06-24 11:19:29.069237]: handleMessage: got handler2
[2015-06-24 11:19:29.069489]: XXX Got msg_id 1  payload [:abort, 666, u'Invalid rpc request (swank:init-project)']
[2015-06-24 11:19:29.069741]: request #1 took 0.00186610221863 seconds
[2015-06-24 11:19:29.101606]: Error shutting down ensime client:
```

**Comment by rorygraves** [comment]
This looks like you have multiple copies of the server started.
Serverlog will always be empty right now as you are launching the server manually via the script.

Make sure that you have updated to the latest code as of last night - it fixes code completions and stuff.

**Comment by schmitch** [comment]
I just git cloned for a bunch of minutes ;)
Also I double checked that I only have one server open.
Maybe the problem is caused, by my sbt project it contains several subprojects?

**Comment by rorygraves** [comment]
Can you try:
1. Stop server
2. clear /Users/schmitch/projects/envisia/envisia-erp-loki/.ensime_cache/ 
3. Restart the server.

The multimodule thing should work without problem.

**Comment by rorygraves** [comment]
I will double check myself on a multi-module project a bit later - but I can't right now - would be surprised if that was broken though.

p.s. thanks for being a brave soul and trying it - its definitely 'experimental' right now whilst its brought back to life

**Comment by schmitch** [comment]
Nah I got it, the problem maybe comes due my project size? I pressed start project and then waited till the commandline of the server outputted some things and then pressed on "root" while I was on the project chooser.
Looks like it takes a bunch of seconds to startup so pressing Cmd + P and pressing Ensime Startup and then quickly choosing my project will fail in a timeout, however waiting in between solves it..

**Comment by rorygraves** [comment]
Good stuff!
yeah, right now its probably worth waiting for "Analyser ready" in the log and then starting the plugin.
Should not matter any more which module you select (Ensime used to run for one module only - not anymore - I will remove the selection box).

Typically if the plugin actually started the process it would wait for the ready messages nicely.

**Comment by rorygraves** [comment]
@schmitch Please let me know your experiences, and what is the biggest pain point right now for you. 
Things that should work right now:
* Jump to definition
* Error highlighting on save
* Completions - (although some of the data is toStringed rather than presented properly right now)
Everything else is 'at risk'
If you do see an error check the console as well as the EnsimeClient log and drop a ticket in (or a PR if you can see the fix it)

**Comment by schmitch** [comment]
Jump to definition works, however its slow on my project,
Currently the completions don't work. Which is the most pain for me. I'm not the best Scala programmer so good autocompletions could save some doc reading. It won't autocomplete simple variables and I tried to clean ensime_cache twice now.

Error checking is broken, too, or I mean Ensime Build works and will print the errors (also is really fast), However it won't print an error in my project:

```
    val x: String = 1

    val hase: Int = "Hase"
```
This is definitly an error case and won't get detected.
However I'm still behind the Idea of Ensime Scala for Sublime since we usually working with IntelliJ and that program is really really sloppy on some of our files.
