### ISSUE TITLE
Ctrl/Cmd-Click does not work for goto method in library files

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-sublime#44]
```

zb_row 1129
Traceback (most recent call last):
  File "/Users/rorygraves/Library/Application Support/Sublime Text 3/Packages/Ensime/rpc.py", line 418, in callback
    on_complete(data)
  File "/Users/rorygraves/Library/Application Support/Sublime Text 3/Packages/Ensime/ensime.py", line 1399, in handle_reply
    zb_col = zb_offset - contents.rfind(newline, 0, zb_offset) - len(newline) if newline else zb_offset
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

Caused by 
Cmd-Click works within your source files, but within libraries you get the above error - this is because the rpc.py SourcePosition.populate method does not understand this form of source position [:type, line, :file, '/workspace/ensime-test-project/.ensime_cache/dep-src/source-jars/java/io/PrintStream.java', :line, 697] and the callback code in EnsimeGoToDefinition.handle_reply does not understand it.

@dickwall @matthughes - FYI

**Comment by rorygraves** [comment]
Fixed in ST3 branch - now supports line file positions correctly.
