### ISSUE TITLE
Ensime fails to parse .ensime

### ISSUE THREAD

**Issue by soc** [ensime/ensime-sublime#63]
I followed the instructions, but when executing `Enisme: Startup` I get the following error message:

```
Ensime has failed to parse the .ensime configuration file at /home/soc/Entwicklung/activator-akka-stream-scala/.ensime because of the following error: 

<class 'SyntaxError'>: unexpected character in read_form: .
(for detailed info refer to Sublime console)

Sublime will now open the offending configuration file for you to fix. Do you wish to proceed?
```

The config looks like this:

```
(
 :root-dir "/home/soc/Entwicklung/activator-akka-stream-scala"
 :cache-dir "/home/soc/Entwicklung/activator-akka-stream-scala/.ensime_cache"
 :name "activator-akka-stream-scala"
 :java-home "/usr/lib/jvm/java-8-openjdk-amd64"
 :java-flags ("-Xms512M" "-Xmx1536M" "-Xss1M" "-XX:+CMSClassUnloadingEnabled")
 :reference-source-roots ("/usr/lib/jvm/java-8-openjdk-amd64/src.zip")
 :scala-version "2.11.7"
 :compiler-args nil
 :formatting-prefs (:doubleIndentClassDeclaration t :alignSingleLineCaseStatements t :alignSingleLineCaseStatements.maxArrowIndent 100 :preserveDanglingCloseParenthesis t)
 :subprojects ((
   :name "activator-akka-stream-scala"
   :module-name "activator-akka-stream-scala"
   :source-roots ("/home/soc/Entwicklung/activator-akka-stream-scala/src/test/scala-2.11" "/home/soc/Entwicklung/activator-akka-stream-scala/src/main/java" "/home/soc/Entwicklung/activator-akka-stream-scala/src/main/scala-2.11" "/home/soc/Entwicklung/activator-akka-stream-scala/src/main/scala" "/home/soc/Entwicklung/activator-akka-stream-scala/src/test/scala" "/home/soc/Entwicklung/activator-akka-stream-scala/src/test/java")
   :target "/home/soc/Entwicklung/activator-akka-stream-scala/target/scala-2.11/classes"
   :test-targets ("/home/soc/Entwicklung/activator-akka-stream-scala/target/scala-2.11/test-classes")
   :depends-on-modules nil
   :compile-deps ("/home/soc/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.12.jar" "/home/soc/.ivy2/cache/com.typesafe.akka/akka-stream-experimental_2.11/jars/akka-stream-experimental_2.11-1.0.jar" "/home/soc/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar" "/home/soc/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar" "/home/soc/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar")
   :runtime-deps nil
   :test-deps nil
   :doc-jars ("/home/soc/.ivy2/cache/org.reactivestreams/reactive-streams/docs/reactive-streams-1.0.0-javadoc.jar" "/home/soc/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/docs/akka-actor_2.11-2.3.12-javadoc.jar" "/home/soc/.ivy2/cache/com.typesafe/config/docs/config-1.2.1-javadoc.jar" "/home/soc/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.11.7-javadoc.jar" "/home/soc/.ivy2/cache/com.typesafe.akka/akka-stream-experimental_2.11/docs/akka-stream-experimental_2.11-1.0-javadoc.jar" "/home/soc/Entwicklung/activator-akka-stream-scala/target/scala-2.11/akka-stream-scala_2.11-1.1-javadoc.jar")
   :reference-source-roots ("/home/soc/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/srcs/akka-actor_2.11-2.3.12-sources.jar" "/home/soc/.ivy2/cache/org.reactivestreams/reactive-streams/srcs/reactive-streams-1.0.0-sources.jar" "/home/soc/.ivy2/cache/com.typesafe.akka/akka-stream-experimental_2.11/srcs/akka-stream-experimental_2.11-1.0-sources.jar" "/home/soc/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.11.7-sources.jar" "/home/soc/.ivy2/cache/com.typesafe/config/srcs/config-1.2.1-sources.jar")))
)
```

**Comment by dickwall** [comment]
Seems to be related to this particular project (since I can open other projects fine). Here's the traceback from the sublime console for reference.

```
Traceback (most recent call last):
  File "/home/dick/.config/sublime-text-3/Packages/Ensime/dotensime.py", line 37, in load
    conf = sexp.read_relaxed(src)
  File "/home/dick/.config/sublime-text-3/Packages/Ensime/sexp.py", line 59, in read_relaxed
    return read_form(s)[0]
  File "/home/dick/.config/sublime-text-3/Packages/Ensime/sexp.py", line 70, in read_form
    return read_list(form)
  File "/home/dick/.config/sublime-text-3/Packages/Ensime/sexp.py", line 101, in read_list
    val, remain = read_form(form)
  File "/home/dick/.config/sublime-text-3/Packages/Ensime/sexp.py", line 70, in read_form
    return read_list(form)
  File "/home/dick/.config/sublime-text-3/Packages/Ensime/sexp.py", line 101, in read_list
    val, remain = read_form(form)
  File "/home/dick/.config/sublime-text-3/Packages/Ensime/sexp.py", line 82, in read_form
    raise SyntaxError('unexpected character in read_form: ' + ch)
  File "<string>", line None
SyntaxError: unexpected character in read_form: .
```
