### ISSUE TITLE
Failure to parse .ensime gives bad feedback

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-sublime#66]
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/home/soc/.config/sublime-text-3/Packages/Ensime/ensime.py", line 1251, in run
    error_handler()
TypeError: 'NoneType' object is not callable
```

Not very helpful....

**Comment by VC1995** [comment]
We give a `BadEnsimeConfig` error now. :D
