### ISSUE TITLE
Ensime: Startup failed without project

### ISSUE THREAD

**Issue by leszekgruchala** [ensime/ensime-sublime#70]
Hi,
I wanted to create new Sublime project using Ensime. From menu I chose Ensime - Startup.
I got following error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "ensime in /Users/lgr/Library/Application Support/Sublime Text 3/Installed Packages/Ensime.sublime-package", line 1251, in run
TypeError: 'NoneType' object is not callable
```

but the docs says:
`If you don't have an Ensime project, the plugin will guide you through creating it.`.

Does it mean I still need to have Sublime project defined?

**Comment by VC1995** [comment]
You've probably moved on but ensime-sublime plugin has been rewritten.
You can follow the instructions at http://ensime.org/editors/sublime/. It's really simple :-)
