### ISSUE TITLE
Ensime throws in debug console when clicking around

### ISSUE THREAD

**Issue by renpillay** [ensime/ensime-sublime#99]
I've installed Ensime (first through Package Control, then got rid of it and cloned the repo directly into Packages).

Each time, when I try to startup Ensime in sublime, I get the following error when clicking around Scala files. Code completion, etc aren't working.

Traceback (most recent call last):
  File "/Users/rpillay/Library/Application Support/Sublime Text 3/Packages/Ensime/rpc.py", line 445, in callback
    data = parser(payload)
  File "/Users/rpillay/Library/Application Support/Sublime Text 3/Packages/Ensime/rpc.py", line 32, in parse
    populate(value_map)
  File "/Users/rpillay/Library/Application Support/Sublime Text 3/Packages/Ensime/rpc.py", line 135, in populate
    self.type_id = m[":type-id"]
KeyError: ':type-id'

I have generated a .ensime file in the root of my project using sbt gen-ensime. The contents of the .ensime seem correct from a brief analysis.

**Comment by aemoncannon** [comment]
@rorygraves Oops. Looks like some fallout from the type-id purge.

**Comment by rorygraves** [comment]
Yep - I checked the calls, failed to check the message parsing - mea culpa - I have a update in progress which should fix this.

**Comment by rorygraves** [comment]
@renpillay Please update to 0.9.0 (Package Control: Update Package) and everything should be working again.
